/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
SimplePluginAudioProcessorEditor::SimplePluginAudioProcessorEditor (SimplePluginAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    for (int i = 0; i < processor.getNumParameters(); ++i) // Add GUI slider/label for
    {                                                      // every parameter in params

        jassert (processor.getParameters()[i]);
        AudioProcessorParameter& param = *processor.getParameters()[i];

        ParameterSlider* newSlider = new ParameterSlider (param);
        jassert (newSlider);
        sliders.add (newSlider);

        newSlider->setSliderStyle (Slider::LinearHorizontal);
        newSlider->setTextBoxStyle (Slider::TextBoxRight,false,unit*8,unit*2);
        newSlider->setColour (Slider::thumbColourId, Colours::silver);
        newSlider->setColour (Slider::textBoxTextColourId, Colour (0xff404040));
        newSlider->setColour (Slider::textBoxBackgroundColourId, Colour (0xff909090));
        newSlider->setDoubleClickReturnValue (true, param.getValue()); // param.getValue() is
                                                                       // now default value
        addAndMakeVisible (newSlider);

        const String name = param.getName(128);
        Label* aLabel = new Label (name, name);
        jassert (aLabel);
        labels.add (aLabel);

        aLabel->setJustificationType (Justification::centredLeft);
        aLabel->setEditable (false, false, false);
        aLabel->setColour (Label::textColourId, Colour (0xff404040));
        aLabel->setColour (TextEditor::textColourId, Colours::black);
        aLabel->setColour (TextEditor::backgroundColourId,Colour (0x00000000));

        addAndMakeVisible (aLabel);
    }
    jassert (processor.getParameters().size() == labels.size());
    jassert (processor.getParameters().size() == sliders.size());

    const int numRows = sliders.size(); // set width and height of editor
    const int height = margin           // (must be set before xtor finished)
                     + numRows * 2 * heightComponent
                     + margin / 2;
    setSize (width, height);
}

SimplePluginAudioProcessorEditor::~SimplePluginAudioProcessorEditor()
{
}

//==============================================================================
void SimplePluginAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::grey);
}

void SimplePluginAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..

    for (int i = 0; i < sliders.size(); ++i)    // Position our GUI elements
    {                                           // according to our relative
        jassert (sliders[i]);                   // layout enum
        sliders[i]->setBounds(margin,
                              margin + i * 2 * heightComponent + 16,
                              widthComponent,
                              heightComponent);
    }

    for (int i = 0; i < labels.size(); ++i)
    {
        jassert (labels[i]);
        labels[i]->setBounds (margin,
                              margin + i * 2 * heightComponent,
                              widthComponent,
                              heightComponent);
    }
}
