/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ParameterSlider.h"


//==============================================================================
/**
    Simple generic editor
    ---------------------
    
    ### Generates sliders automatically from parameters in plugin processor

    Uses processor 'params' container to get details about the parameters
    (instead of specifying each slider individually as normal). We loop through 
    the params in the constructor and generate a slider and a label for each 
    parameter (dynamically on the heap. We use OwnedArrays to manage ownership 
    and delete). The resized() function positions the sliders according to our
    RelativeLayout enum.
    
    We override sliderValueChanged() to update the processor parameter through
    the public setParam() function. A timer callback syncs the GUI sliders with 
    the processor parameters at the rate of 30Hz.

*/
class SimplePluginAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    SimplePluginAudioProcessorEditor (SimplePluginAudioProcessor&);
    ~SimplePluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    OwnedArray<ParameterSlider> sliders;
    OwnedArray<Label> labels;
    
    enum RelativeLayout                                       // Measurements for
    {                                                         // relative GUI layout
        unit = 8, // pixels
        width = 64 * unit,
        margin = 2 * unit,
        widthComponent = width - margin * 2,
        heightComponent = 3 * unit
    };

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    SimplePluginAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SimplePluginAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
